Repository DhanrajKamble/ThePokedex, pull requests merged in 2023-11, with the labels that each got.

#12 fix: Fixed the link to contributors.md file
  .github/PULL_REQUEST_TEMPLATE.md
Labels: bug

#15 fix: Added footer
  index.html
Labels: good first issue

#17 fix: Changed Home Page layout
  index.html
  style.css
Labels: good first issue

#22 Fixed : Hover Search Button
  index.html
  style.css
Labels: good first issue

#24 fix: fixed merge conflict text in footer
  index.html
Labels: bug

#30 fix: added responsiveness to the navbar section
  style.css
Labels: enhancement, good first issue

#41 fix: Background Color
  style.css
Labels: bug

#45 feat: created the footer
  images/go-hub-logo.svg
  index.html
  style.css
Labels: enhancement, good first issue

#48 fix: adding font size of title in media querey for mobile size screen
  style.css
Labels: bug, enhancement, good first issue

#51 fix: added the padding in menu card for mobile size screen and also make s…
  index.html
  style.css
Labels: bug, enhancement, good first issue
